# Numpy Basic

* Numpy 是處理 Array 的常用模組。
* Array 是多維的陣列(list)，Numpy 有各種針對Array的數學計算功能，補強 python 的不足，例如平均值、變異數或矩陣運算等。
* 安裝 Anaconda 後就會自動安裝 numpy, 不需另行安裝。

In [1]:
# 把模組叫進來。
import numpy as np
path='d:/My Python/'    # 資料庫儲存的位置

In [1]:
import numpy as np
path = 'C:/Users/HSIU/Desktop/108-1/python_ntu'

# np.array() 製作一個 array

## from List to np.array

In [2]:
# 一個維度
a1=[1, 2, 3, 4, 5]
a = np.array(a1)  # list 轉為 array
print (type(a))
a

<class 'numpy.ndarray'>


array([1, 2, 3, 4, 5])

In [3]:
# 印出第一個與第二個元素
print (a[0])
print (a[1])

1
2


## from np.array to List

In [4]:
# numpy array 直接轉換為 list
b=list(a)
print (type(b))
b

<class 'list'>


[1, 2, 3, 4, 5]

## np.linspace(,,) 產生等距的數列 

In [5]:
# 從 0 到 10，5個元素，
a= np.linspace(0,10,5)  
print (len(a))
print (type(a))
print (a)

5
<class 'numpy.ndarray'>
[ 0.   2.5  5.   7.5 10. ]


In [6]:
# 逐一印出檢查一下
for i in a:
    print (i)

0.0
2.5
5.0
7.5
10.0


In [7]:
# 存成 list 
num=list(a)
num

[0.0, 2.5, 5.0, 7.5, 10.0]

## np.arange() 依一定間距，產生數列

In [8]:
# 從 0 到 10，間距為 2，
c=np.arange(0,10,2)      # define interval
print (len(c))
print (type(c))
print (list(c))   # 轉成 list

5
<class 'numpy.ndarray'>
[0, 2, 4, 6, 8]


## 比較 range() 與 np.arrange()
* 與 np.arrange() 類同

In [9]:
c2=range(0,10,2)
print (list(c2))   # 轉成 list

[0, 2, 4, 6, 8]


# 多維度的 array

In [10]:
# 兩個維度
a1=[1,2,3,4,5]
a2=[6,7,8,9,10]
a3=[11,12,13,14,15]
a = np.array([a1,a2,a3])   
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [2]:
a1=[1,2,3,4,5]
a2=[6,7,8,9,10]
a3=[11,12,13,14,15]
a = np.array([a1, a2, a3])
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [11]:
# 直接轉 list 會變成這樣
print (list(a))

[array([1, 2, 3, 4, 5]), array([ 6,  7,  8,  9, 10]), array([11, 12, 13, 14, 15])]


In [12]:
# 轉為我們熟悉的 list 格式
print ([list(a[0]),list(a[1]),list(a[2])])

[[1, 2, 3, 4, 5], [6, 7, 8, 9, 10], [11, 12, 13, 14, 15]]


In [4]:
print([list(a[0]), list(a[1]), list(a[2])])

[[1, 2, 3, 4, 5], [6, 7, 8, 9, 10], [11, 12, 13, 14, 15]]


## reshape() 由一維變為多維

In [13]:
# 變成兩維的陣列，前者為第一層，後者為第二層
# 注意個數必須一致，3*5=15，否則會出現 error
a = np.arange(15).reshape(3, 5)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [6]:
a = np.arange(15).reshape(3, 5)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [8]:
# 用 index 篩選
print (a[0])
print (a[0][:])   # 冒號代表全部
# row 1, column 2，注意從 0 開始啟算 
# 讀取某個元素的值
print (a[1][2])

[0 1 2 3 4]
[0 1 2 3 4]
7


## np.ones() 元素均為 1 的 array

In [15]:
# 兩層的 array
b = np.ones((4,5))   # Create an array of all ones
b

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

## np.zeros() 元素均為 0 的 array

In [16]:
# 兩層的 array
b = np.zeros((4,5))   # Create an array of all ones
b

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

## 改變array中某個元素值

In [17]:
b[1][2]=100
b

array([[  0.,   0.,   0.,   0.,   0.],
       [  0.,   0., 100.,   0.,   0.],
       [  0.,   0.,   0.,   0.,   0.],
       [  0.,   0.,   0.,   0.,   0.]])

# 隨機抽樣
* https://docs.scipy.org/doc/numpy-1.13.0/reference/routines.random.html

## np.random.random(n) 從0到1隨機抽樣，抽n個

In [18]:
# 一個維度，隨機取 n 個，機率都一樣
e = np.random.random(10)  # np.random為一模組
e

array([0.65930089, 0.54018644, 0.25015378, 0.93686268, 0.58961866,
       0.15653505, 0.43180047, 0.86921536, 0.51402601, 0.75190345])

In [19]:
# 兩個維度
# 0~1 常態分布抽樣，隨機值，第一層四個元素，第二層五個元素
e = np.random.random((4,5)) 
e

array([[0.38510098, 0.47425708, 0.28755815, 0.51700124, 0.29125459],
       [0.0588957 , 0.51902222, 0.30806312, 0.35678676, 0.04957358],
       [0.4594658 , 0.67383264, 0.74009678, 0.49339211, 0.35933947],
       [0.61099088, 0.51118186, 0.91199767, 0.1942769 , 0.54126483]])

## np.random.randint(n,m,k) 整數隨機抽樣，從n到m抽k個

In [20]:
# 整數隨機抽樣，從n到m抽k個
e = np.random.randint(1,10,10) 
e

array([4, 8, 7, 4, 8, 2, 3, 1, 7, 9])

## np.random.standard_normal(n) 標準常態分佈抽 n 個

In [21]:
#  標準常態分佈抽 n 個
e = np.random.standard_normal(10) 
e

array([-0.37511405,  1.4084211 ,  1.76945806, -0.1615309 ,  0.06162014,
        0.96928469,  1.51467059,  1.96233511, -1.28168525,  0.34130373])

## np.random.normal(u,s,n) 常態分佈，平均值 u, 標準差 s，抽 n 個

In [22]:
# 常態分佈，平均值 u, 標準差 s，抽 n 個
# u=60，s= 7，n= 10
# normal()
e = np.random.normal(60,7,10) 
e

array([57.60727401, 51.50733385, 56.95165948, 57.54406023, 45.91063495,
       66.52335826, 65.41797036, 61.7007907 , 59.84830894, 54.54122919])

## np.random.uniform(a,b,n) 均等分佈，從a到b，抽 n 個

In [23]:
# 均等分佈，從a到b，抽 n 個
# a=1, b=10, n=10
e = np.random.uniform(1,10,10)
e

array([2.91029701, 9.66137317, 4.28305531, 1.85592339, 5.43902654,
       4.61350149, 3.31403693, 7.82537345, 6.92343442, 4.05248809])

## .vstack([a,b]) 垂直合併

In [24]:
# 垂值合併
a = np.ones((4,5))   # 隨機選取常態分佈值  
b = np.zeros((4,5))   # 隨機選取常態分佈值
c=np.vstack([a,b])
c

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [11]:
a = np.ones((4, 5))
b = np.zeros((4, 5))
c = np.vstack([a, b])
c

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

##  .htack([a,b]) 水平合併

In [25]:
# 水平合併
d=np.hstack([a,b])
d

array([[1., 1., 1., 1., 1., 0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1., 0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1., 0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1., 0., 0., 0., 0., 0.]])

In [26]:
## 如果維度不對，則出現錯誤訊息（4,4) (2,8)
import sys
try:
    e=np.hstack([c,d])
    e
except:
    print ('something wrong, numbers not match')

something wrong, numbers not match


In [12]:
import sys
try:
    e = np.hstack([c, d])
    e
except:
    print('something wrong, numbers not match')

something wrong, numbers not match


# 練習__
* 擲骰子，一次擲三個，計算點數總和。總共擲100次，記錄每次擲的點數。

In [16]:
a=np.random.randint(1,6,3)
for i in range(49): #只有49次，不是從0開始計算
    c=np.random.randint(1,7,3)
    #print(c)
    # 垂直往下加
    a=np.vstack([a,c])
a  

[2 4 1]
[3 1 5]


In [48]:
a = np.random.randint(1, 7, 3)
for i in range(49):
    c = np.random.randint(1, 7, 3)
    a = np.vstack([a, c])
a

array([[1, 1, 1],
       [5, 6, 2],
       [3, 4, 5],
       [3, 5, 5],
       [5, 1, 2],
       [4, 2, 1],
       [6, 6, 3],
       [6, 1, 1],
       [4, 6, 6],
       [3, 6, 6],
       [3, 1, 3],
       [4, 1, 1],
       [4, 2, 3],
       [4, 2, 5],
       [1, 6, 4],
       [5, 1, 6],
       [3, 4, 2],
       [4, 6, 1],
       [6, 2, 1],
       [4, 4, 5],
       [2, 6, 1],
       [3, 3, 3],
       [6, 4, 5],
       [6, 3, 1],
       [3, 1, 5],
       [2, 2, 2],
       [6, 3, 4],
       [2, 2, 6],
       [5, 3, 3],
       [2, 6, 5],
       [5, 2, 1],
       [6, 3, 4],
       [2, 2, 3],
       [3, 6, 1],
       [4, 6, 4],
       [6, 6, 2],
       [2, 1, 5],
       [6, 5, 2],
       [2, 1, 2],
       [4, 3, 4],
       [4, 3, 1],
       [4, 5, 4],
       [4, 3, 2],
       [4, 4, 5],
       [2, 5, 4],
       [4, 6, 3],
       [2, 5, 3],
       [4, 4, 6],
       [4, 4, 4],
       [6, 5, 3]])

## 顯示array 的資訊 .dtype, .shape,  .ndim, .size

In [28]:
a.dtype # 元素型態

dtype('int32')

In [19]:
a.dtype

dtype('int32')

In [29]:
a.ndim  #  dimention #維度

2

In [20]:
a.ndim

2

In [30]:
a.shape  # rows, columns

(50, 3)

In [21]:
a.shape

(50, 3)

In [31]:
a.size  # 總共元素個數

150

In [22]:
a.size

150

# indexing and slicing of array elements

In [32]:
print (len(a))
# 每次擲骰子的第一個點數
a[:,0]

50


array([4, 4, 5, 1, 2, 4, 6, 3, 6, 2, 4, 3, 1, 2, 4, 5, 6, 5, 5, 6, 1, 1,
       1, 6, 2, 5, 3, 1, 6, 3, 5, 1, 4, 6, 6, 6, 1, 1, 5, 6, 4, 4, 4, 1,
       3, 3, 2, 3, 5, 4])

In [33]:
# 第三次擲骰子的點數
a[2,:]

array([5, 2, 4])

In [34]:
# 最後一次擲的骰子
a[-1]

array([4, 6, 2])

## sort()

In [23]:
# 各欄獨立，分別排序。第一個維度，各元素同樣位置的元素排序
a0=np.sort(a, axis=0)  #拆開欄獨立
a0

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 2, 1],
       [1, 2, 1],
       [1, 2, 2],
       [1, 3, 2],
       [1, 3, 2],
       [2, 3, 2],
       [2, 3, 2],
       [2, 3, 2],
       [2, 3, 2],
       [2, 3, 2],
       [2, 4, 2],
       [2, 4, 2],
       [3, 4, 3],
       [3, 4, 3],
       [3, 4, 3],
       [4, 4, 3],
       [4, 4, 3],
       [4, 4, 4],
       [4, 4, 4],
       [4, 5, 4],
       [4, 5, 4],
       [4, 5, 4],
       [4, 5, 4],
       [4, 5, 4],
       [4, 5, 4],
       [4, 5, 4],
       [4, 5, 4],
       [5, 5, 4],
       [5, 5, 4],
       [5, 5, 5],
       [5, 5, 5],
       [5, 5, 5],
       [5, 5, 5],
       [6, 6, 5],
       [6, 6, 5],
       [6, 6, 5],
       [6, 6, 5],
       [6, 6, 5],
       [6, 6, 6],
       [6, 6, 6],
       [6, 6, 6],
       [6, 6, 6],
       [6, 6, 6]])

In [36]:
# 各列獨立，分別排序，第二個維度，各元素排序
a1=np.sort(a, axis=1)   #各列獨立
a1

array([[1, 2, 4],
       [1, 4, 6],
       [2, 4, 5],
       [1, 3, 4],
       [1, 2, 3],
       [2, 4, 4],
       [1, 4, 6],
       [3, 5, 6],
       [1, 3, 6],
       [2, 5, 6],
       [4, 5, 6],
       [3, 3, 6],
       [1, 2, 4],
       [2, 2, 6],
       [3, 3, 4],
       [4, 5, 6],
       [2, 4, 6],
       [2, 5, 5],
       [2, 3, 5],
       [5, 5, 6],
       [1, 3, 4],
       [1, 1, 4],
       [1, 1, 2],
       [6, 6, 6],
       [1, 2, 3],
       [3, 5, 5],
       [3, 4, 6],
       [1, 3, 3],
       [1, 6, 6],
       [3, 3, 5],
       [2, 3, 5],
       [1, 3, 3],
       [1, 4, 5],
       [2, 4, 6],
       [2, 4, 6],
       [1, 2, 6],
       [1, 2, 2],
       [1, 5, 5],
       [1, 2, 5],
       [3, 5, 6],
       [3, 4, 6],
       [2, 4, 6],
       [4, 4, 6],
       [1, 1, 1],
       [3, 3, 5],
       [3, 4, 4],
       [2, 2, 3],
       [3, 4, 5],
       [1, 5, 5],
       [2, 4, 6]])

In [37]:
# 所有元素值依大小排序
a3=np.sort(a, axis=None)
a3

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
       3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4,
       4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 5, 5, 5, 5, 5, 5, 5, 5,
       5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 6, 6, 6, 6, 6, 6, 6,
       6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6])

## 比較 擲骰子，存為list of list

In [38]:
b=[]
for i in range(49):
    c=np.random.randint(1,7,3)
    # 垂直往下加
    b.append(list(c))
b[:10]  

[[5, 4, 6],
 [5, 6, 4],
 [4, 6, 6],
 [2, 1, 6],
 [5, 3, 3],
 [2, 4, 6],
 [6, 6, 3],
 [4, 5, 2],
 [6, 3, 1],
 [6, 1, 5]]

In [24]:
b = []
for i in range(49):
    c=np.random.randint(1, 7, 3)
    b.append(c)
b[:10]

[array([4, 3, 1]),
 array([1, 4, 6]),
 array([2, 1, 3]),
 array([6, 4, 3]),
 array([3, 3, 2]),
 array([6, 1, 2]),
 array([1, 4, 6]),
 array([3, 1, 2]),
 array([1, 5, 3]),
 array([4, 1, 3])]

In [39]:
# 根據第一欄排序
#比較list和array排序的差異
b1=sorted(b,key=lambda x:x[0],reverse=False)
b1[:10]

[[1, 5, 6],
 [1, 6, 1],
 [1, 6, 6],
 [1, 4, 1],
 [1, 2, 5],
 [2, 1, 6],
 [2, 4, 6],
 [2, 2, 1],
 [2, 1, 2],
 [2, 2, 3]]

In [25]:
b1= sorted(b, key = lambda x:x[0], reverse = False)
b1[:10]

[array([1, 4, 6]),
 array([1, 4, 6]),
 array([1, 5, 3]),
 array([1, 3, 3]),
 array([1, 2, 4]),
 array([1, 3, 6]),
 array([1, 5, 2]),
 array([1, 6, 3]),
 array([2, 1, 3]),
 array([2, 1, 5])]

In [40]:
# 根據第二欄排序
b2=sorted(b,key=lambda x:x[1],reverse=False)
b2[:10]  #在array中，排序是以"維度"來看，會打掉原本的組合，而list中的排序則是以欄的位置來看

[[2, 1, 6],
 [6, 1, 5],
 [5, 1, 5],
 [2, 1, 2],
 [5, 1, 2],
 [6, 1, 2],
 [4, 1, 3],
 [5, 1, 2],
 [6, 1, 6],
 [3, 1, 6]]

## 篩選 numpy array

In [41]:
# 大於 10 的 array
b=(a[a > 5])
b

array([6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6,
       6, 6, 6])

## 數學函數 sum(), cumsum(), average(), std()
* 數學函數 https://docs.scipy.org/doc/numpy/reference/routines.math.html 

In [42]:
# 最大值最小值
print (np.min(a))
print (np.max(a))

1
6


In [67]:
# 各欄或列加總 .sum()
print(a)
print (np.sum(a))  # Compute sum of all elements; prints "10"
print (np.sum(a, axis=0))  # Compute sum of each column; prints "[4 6]" #axis = 0 代表欄
print (np.sum(a, axis=1))  # Compute sum of each row; prints "[3 7]" #axis = 1 代表列

[[4 2 1]
 [4 6 1]
 [5 2 4]
 [1 4 3]
 [2 1 3]
 [4 4 2]
 [6 4 1]
 [3 6 5]
 [6 3 1]
 [2 5 6]
 [4 5 6]
 [3 3 6]
 [1 4 2]
 [2 2 6]
 [4 3 3]
 [5 4 6]
 [6 2 4]
 [5 5 2]
 [5 3 2]
 [6 5 5]
 [1 4 3]
 [1 4 1]
 [1 1 2]
 [6 6 6]
 [2 1 3]
 [5 5 3]
 [3 6 4]
 [1 3 3]
 [6 6 1]
 [3 5 3]
 [5 2 3]
 [1 3 3]
 [4 1 5]
 [6 4 2]
 [6 4 2]
 [6 1 2]
 [1 2 2]
 [1 5 5]
 [5 2 1]
 [6 5 3]
 [4 6 3]
 [4 6 2]
 [4 4 6]
 [1 1 1]
 [3 5 3]
 [3 4 4]
 [2 2 3]
 [3 5 4]
 [5 5 1]
 [4 6 2]]
523
[181 187 155]
[ 7 11 11  8  6 10 11 14 10 13 15 12  7 10 10 15 12 12 10 16  8  6  4 18
  6 13 13  7 13 11 10  7 10 12 12  9  5 11  8 14 13 12 14  3 11 11  7 12
 11 12]


In [44]:
# 每次擲骰子的點數總合，排序
score=np.sort(np.sum(a, axis=1))
score

array([ 3,  4,  5,  6,  6,  6,  7,  7,  7,  7,  7,  8,  8,  8,  9, 10, 10,
       10, 10, 10, 10, 10, 11, 11, 11, 11, 11, 11, 11, 11, 12, 12, 12, 12,
       12, 12, 12, 12, 13, 13, 13, 13, 13, 14, 14, 14, 15, 15, 16, 18])

In [26]:
score  = np.sort(np.sum(a, axis =1))
score

array([ 5,  6,  6,  7,  7,  7,  7,  7,  7,  8,  8,  8,  8,  8,  9,  9,  9,
        9,  9, 10, 10, 10, 10, 11, 11, 11, 11, 11, 12, 12, 12, 12, 12, 12,
       12, 13, 13, 13, 13, 13, 14, 14, 14, 14, 15, 15, 16, 16, 17, 17])

In [27]:
# 大於15的次數
b=len((score[score>=15]))
b

6

In [46]:
# 依欄累計加總 .cumsum()
a0=a.cumsum(axis=0)                         # cumulative sum along each column
a0

array([[  4,   2,   1],
       [  8,   8,   2],
       [ 13,  10,   6],
       [ 14,  14,   9],
       [ 16,  15,  12],
       [ 20,  19,  14],
       [ 26,  23,  15],
       [ 29,  29,  20],
       [ 35,  32,  21],
       [ 37,  37,  27],
       [ 41,  42,  33],
       [ 44,  45,  39],
       [ 45,  49,  41],
       [ 47,  51,  47],
       [ 51,  54,  50],
       [ 56,  58,  56],
       [ 62,  60,  60],
       [ 67,  65,  62],
       [ 72,  68,  64],
       [ 78,  73,  69],
       [ 79,  77,  72],
       [ 80,  81,  73],
       [ 81,  82,  75],
       [ 87,  88,  81],
       [ 89,  89,  84],
       [ 94,  94,  87],
       [ 97, 100,  91],
       [ 98, 103,  94],
       [104, 109,  95],
       [107, 114,  98],
       [112, 116, 101],
       [113, 119, 104],
       [117, 120, 109],
       [123, 124, 111],
       [129, 128, 113],
       [135, 129, 115],
       [136, 131, 117],
       [137, 136, 122],
       [142, 138, 123],
       [148, 143, 126],
       [152, 149, 129],
       [156, 155

In [47]:
# 依列累計加總
a1=a.cumsum(axis=1)                         # cumulative sum along each row
a1

array([[ 4,  6,  7],
       [ 4, 10, 11],
       [ 5,  7, 11],
       [ 1,  5,  8],
       [ 2,  3,  6],
       [ 4,  8, 10],
       [ 6, 10, 11],
       [ 3,  9, 14],
       [ 6,  9, 10],
       [ 2,  7, 13],
       [ 4,  9, 15],
       [ 3,  6, 12],
       [ 1,  5,  7],
       [ 2,  4, 10],
       [ 4,  7, 10],
       [ 5,  9, 15],
       [ 6,  8, 12],
       [ 5, 10, 12],
       [ 5,  8, 10],
       [ 6, 11, 16],
       [ 1,  5,  8],
       [ 1,  5,  6],
       [ 1,  2,  4],
       [ 6, 12, 18],
       [ 2,  3,  6],
       [ 5, 10, 13],
       [ 3,  9, 13],
       [ 1,  4,  7],
       [ 6, 12, 13],
       [ 3,  8, 11],
       [ 5,  7, 10],
       [ 1,  4,  7],
       [ 4,  5, 10],
       [ 6, 10, 12],
       [ 6, 10, 12],
       [ 6,  7,  9],
       [ 1,  3,  5],
       [ 1,  6, 11],
       [ 5,  7,  8],
       [ 6, 11, 14],
       [ 4, 10, 13],
       [ 4, 10, 12],
       [ 4,  8, 14],
       [ 1,  2,  3],
       [ 3,  8, 11],
       [ 3,  7, 11],
       [ 2,  4,  7],
       [ 3,  

In [32]:
# 平均值 .average()
print (np.average(a, axis=0))
print (np.average(a, axis=1))
print (np.average(a[0]))
print (np.average(a[:,0]))

[3.46 4.   3.34]
[3.         4.         3.         4.33333333 2.33333333 2.33333333
 5.         2.66666667 4.         3.         4.         4.33333333
 2.33333333 2.66666667 3.66666667 3.33333333 4.66666667 2.66666667
 2.         3.         2.33333333 5.33333333 3.33333333 2.33333333
 4.         4.66666667 4.33333333 4.         3.66666667 4.66666667
 3.66666667 4.66666667 3.66666667 5.66666667 4.         5.
 4.         2.66666667 3.33333333 2.66666667 3.33333333 2.
 2.33333333 3.         5.33333333 4.33333333 1.66666667 4.33333333
 5.66666667 3.66666667]
3.0
3.46


In [30]:
# 計算各列的加權平均值，依序列加權
wei=np.arange(0,50,1)
# print(wei)
# print(np.average(a[:, 0]))
print (np.average(a[:,0], weights=wei)) #透過weights參數來進行加權

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49]
3.46
3.608979591836735


In [50]:
# 標準差
print (np.std(a))
print (np.std(a, axis=0))
print (np.std(a, axis=1))

1.696021488333473
[1.77640086 1.62246726 1.61554944]
[1.24721913 2.05480467 1.24721913 1.24721913 0.81649658 0.94280904
 2.05480467 1.24721913 2.05480467 1.69967317 0.81649658 1.41421356
 1.24721913 1.88561808 0.47140452 0.81649658 1.63299316 1.41421356
 1.24721913 0.47140452 1.24721913 1.41421356 0.47140452 0.
 0.81649658 0.94280904 1.24721913 0.94280904 2.3570226  0.94280904
 1.24721913 0.94280904 1.69967317 1.63299316 1.63299316 2.1602469
 0.47140452 1.88561808 1.69967317 1.24721913 1.24721913 1.63299316
 0.94280904 0.         0.94280904 0.47140452 0.47140452 0.81649658
 1.88561808 1.63299316]


## exp(), sqrt()

In [34]:
# 指數 #指数函数是数学中重要的函数。应用到值e上的这个函数写为exp(x)。还可以等价的写为ex，这里的e是数学常数，就是自然对数的底数，近似等于 2.718281828，还称为欧拉数
np.exp(a)
#print(np.exp(0))

array([[  2.71828183, 403.42879349,   7.3890561 ],
       [ 54.59815003,  54.59815003,  54.59815003],
       [ 54.59815003,   2.71828183,  54.59815003],
       [ 54.59815003, 403.42879349,  20.08553692],
       [ 54.59815003,   2.71828183,   7.3890561 ],
       [  2.71828183, 148.4131591 ,   2.71828183],
       [148.4131591 , 148.4131591 , 148.4131591 ],
       [  2.71828183, 148.4131591 ,   7.3890561 ],
       [ 20.08553692,  54.59815003, 148.4131591 ],
       [ 54.59815003,  54.59815003,   2.71828183],
       [  2.71828183, 403.42879349, 148.4131591 ],
       [403.42879349,   2.71828183, 403.42879349],
       [  7.3890561 ,   2.71828183,  54.59815003],
       [403.42879349,   2.71828183,   2.71828183],
       [148.4131591 , 148.4131591 ,   2.71828183],
       [  7.3890561 , 403.42879349,   7.3890561 ],
       [403.42879349,  54.59815003,  54.59815003],
       [  2.71828183,   2.71828183, 403.42879349],
       [  2.71828183,  54.59815003,   2.71828183],
       [  7.3890561 ,  20.08553

In [35]:
# 開根號
#np.sqrt(a)
np.sqrt(a)

array([[1.        , 2.44948974, 1.41421356],
       [2.        , 2.        , 2.        ],
       [2.        , 1.        , 2.        ],
       [2.        , 2.44948974, 1.73205081],
       [2.        , 1.        , 1.41421356],
       [1.        , 2.23606798, 1.        ],
       [2.23606798, 2.23606798, 2.23606798],
       [1.        , 2.23606798, 1.41421356],
       [1.73205081, 2.        , 2.23606798],
       [2.        , 2.        , 1.        ],
       [1.        , 2.44948974, 2.23606798],
       [2.44948974, 1.        , 2.44948974],
       [1.41421356, 1.        , 2.        ],
       [2.44948974, 1.        , 1.        ],
       [2.23606798, 2.23606798, 1.        ],
       [1.41421356, 2.44948974, 1.41421356],
       [2.44948974, 2.        , 2.        ],
       [1.        , 1.        , 2.44948974],
       [1.        , 2.        , 1.        ],
       [1.41421356, 1.73205081, 2.        ],
       [1.        , 2.23606798, 1.        ],
       [2.44948974, 2.23606798, 2.23606798],
       [1.

# 矩陣運算

In [53]:
#identity matrix 單位矩陣
I = np.eye(4)  
print (I)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [36]:
I = np.eye(4)
print(I)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [39]:
x = np.array([[1,2,3,4],[3,4,5,6]])
y = np.array([[5,6,7,8],[7,8,9,10]])
print (x)
print (y)

[[1 2 3 4]
 [3 4 5 6]]
[[ 5  6  7  8]
 [ 7  8  9 10]]


In [55]:
# 轉置矩陣
xt=x.T
xt

array([[1, 3],
       [2, 4],
       [3, 5],
       [4, 6]])

## 矩陣的加減乘除


In [56]:
# 加
xay=x+y
xay

array([[ 6,  8, 10, 12],
       [10, 12, 14, 16]])

In [57]:
np.add(x, y)

array([[ 6,  8, 10, 12],
       [10, 12, 14, 16]])

In [58]:
# 減
np.subtract(x, y)

array([[-4, -4, -4, -4],
       [-4, -4, -4, -4]])

In [59]:
# 元素兩兩相乘
xpy=x*y
xpy

array([[ 5, 12, 21, 32],
       [21, 32, 45, 60]])

In [60]:
np.multiply(x, y)

array([[ 5, 12, 21, 32],
       [21, 32, 45, 60]])

In [43]:
# 內積，矩陣相乘，注意 dot 與 multiply 不同
# 轉置後方能相乘 2*4, 4*2
print(x)
print(y.T)
np.dot(x, y.T)
print(x.dot(y.T)) #row1*col1, row1*col2, row2*col1, row2*col2

[[1 2 3 4]
 [3 4 5 6]]
[[ 5  7]
 [ 6  8]
 [ 7  9]
 [ 8 10]]
[[ 70  90]
 [122 158]]
90


In [62]:
# 元素兩兩相除
xdy=x/y
xdy

array([[0.2       , 0.33333333, 0.42857143, 0.5       ],
       [0.42857143, 0.5       , 0.55555556, 0.6       ]])

## 反矩陣 np.linalg.inv()

In [63]:
xdy=x.dot(y.T)
inv_x = np.linalg.inv(xdy)
print (inv_x)

[[ 1.975 -1.125]
 [-1.525  0.875]]


In [64]:
# 矩陣和自己的反矩陣相乘等於單位矩陣
np.dot(xdy,inv_x)

array([[1., 0.],
       [0., 1.]])

## save(,), load(,) array

In [44]:
# save an array
np.save(path + "/data/example.npy",b)

In [47]:
a1=np.load(path + "/data/example.npy")
a1
print(a1)

6


## numpy save and load dictionary
* 用pickle 亦可儲存 dictionarfy

In [ ]:
## zip( ) 將兩個List 配對結合，再轉為字典變數
names = ['One', 'Two', 'Three', 'Four']
numbers = [1, 2, 3, 4]
d2 = zip(names,numbers)
dic1 = dict(d2)
print (dic1)

In [ ]:
# path/dic1 為檔案儲存的路徑，必須存在這個資料夾
np.save(path + "data/dic1.npy", dic1)

In [ ]:
dic1=np.load(path + "data/dic1.npy")
print (dic1)

# 提示
* numpy array 與 list 類同，可以進行多維度的資料整理，彼此也可以轉換。
* numpy 加強數學運算的功能。特別是抽樣，與矩陣運算，甚為常用。
* numpy array 裡面的元素，只能是數字，不能是字串、list 等其他的變數型態，list 則無此限制。

# 作業
* 擲骰子，每次擲十個，共鄭一千次。每次擲骰子十個點數之和大於50的機率有多少? 
* 請用 numpy.random 抽樣，計算大於50的次數與總共次數的比例，即可得機率。

In [ ]:
#cumsum 計算10個點數的總和

