# Numpy Basic

* Numpy 是處理 Array 的常用模組。
* Array 是多維的陣列(list)，Numpy 有各種針對Array的數學計算功能，補強 python 的不足，例如平均值、變異數或矩陣運算等。
* 安裝 Anaconda 後就會自動安裝 numpy, 不需另行安裝。

In [2]:
# 把模組叫進來。
import numpy as np
path='d:/My Python/'    # 資料庫儲存的位置

# np.array() 製作一個 array

## from List to np.array

In [5]:
# 一個維度
a1=[1, 2, 3, 4, 5]
a = np.array(a1)  # list 轉為 array
print (type(a))
a

<class 'numpy.ndarray'>


array([1, 2, 3, 4, 5])

In [11]:
# 印出第一個與第二個元素
print (a[0])
print (a[1])

1
2


## from np.array to List

In [12]:
# numpy array 直接轉換為 list
b=list(a)
print (type(b))
b

<class 'list'>


[1, 2, 3, 4, 5]

## np.linspace(,,) 產生等距的數列 

In [16]:
# 從 0 到 10，5個元素，
a= np.linspace(0,10,5)  
print (len(a))
print (type(a))
print (a)

5
<class 'numpy.ndarray'>
[ 0.   2.5  5.   7.5 10. ]


In [17]:
# 逐一印出檢查一下
for i in a:
    print (i)

0.0
2.5
5.0
7.5
10.0


In [18]:
# 存成 list 
num=list(a)
num

[0.0, 2.5, 5.0, 7.5, 10.0]

## np.arange() 依一定間距，產生數列

In [23]:
# 從 0 到 10，間距為 2，
c=np.arange(0,10,2)      # define interval
print (len(c))
print (type(c))
print (list(c))   # 轉成 list

5
<class 'numpy.ndarray'>
[0, 2, 4, 6, 8]


## 比較 range() 與 np.arrange()
* 與 np.arrange() 類同

In [26]:
c2=range(0,10,2)
print (list(c2))   # 轉成 list

[0, 2, 4, 6, 8]


# 多維度的 array

In [27]:
# 兩個維度
a1=[1,2,3,4,5]
a2=[6,7,8,9,10]
a3=[11,12,13,14,15]
a = np.array([a1,a2,a3])   
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [31]:
# 直接轉 list 會變成這樣
print (list(a))

[array([1, 2, 3, 4, 5]), array([ 6,  7,  8,  9, 10]), array([11, 12, 13, 14, 15])]


In [32]:
# 轉為我們熟悉的 list 格式
print ([list(a[0]),list(a[1]),list(a[2])])

[[1, 2, 3, 4, 5], [6, 7, 8, 9, 10], [11, 12, 13, 14, 15]]


## reshape() 由一維變為多維

In [40]:
# 變成兩維的陣列，前者為第一層，後者為第二層
# 注意個數必須一致，3*5=15，否則會出現 error
a = np.arange(15).reshape(3, 5)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [48]:
# 用 index 篩選
print (a[0])
print (a[0][:])   # 冒號代表全部
# row 1, column 2，注意從 0 開始啟算 
# 讀取某個元素的值
print (a[1][2])

[0 1 2 3 4]
[0 1 2 3 4]
7


## np.ones() 元素均為 1 的 array

In [44]:
# 兩層的 array
b = np.ones((4,5))   # Create an array of all ones
b

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

## np.zeros() 元素均為 0 的 array

In [45]:
# 兩層的 array
b = np.zeros((4,5))   # Create an array of all ones
b

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

## 改變array中某個元素值

In [46]:
b[1][2]=100
b

array([[  0.,   0.,   0.,   0.,   0.],
       [  0.,   0., 100.,   0.,   0.],
       [  0.,   0.,   0.,   0.,   0.],
       [  0.,   0.,   0.,   0.,   0.]])

# 隨機抽樣
* https://docs.scipy.org/doc/numpy-1.13.0/reference/routines.random.html

## np.random.random(n) 從0到1隨機抽樣，抽n個

In [49]:
# 一個維度，隨機取 n 個，機率都一樣
e = np.random.random(10) 
e

array([0.14543237, 0.60621923, 0.95689727, 0.8283155 , 0.132521  ,
       0.07716155, 0.83582217, 0.44532936, 0.88804271, 0.10727936])

In [53]:
# 兩個維度
# 0~1 常態分布抽樣，隨機值，第一層四個元素，第二層五個元素
e = np.random.random((4,5)) 
e

array([[0.54756201, 0.51168896, 0.90057346, 0.29401511, 0.0136724 ],
       [0.45042176, 0.25378539, 0.11144029, 0.82534245, 0.73209186],
       [0.80015948, 0.76652083, 0.86529372, 0.5744882 , 0.61237703],
       [0.0294238 , 0.09535419, 0.57409875, 0.05397395, 0.84451406]])

## np.random.randint(n,m,k) 整數隨機抽樣，從n到m抽k個

In [54]:
# 整數隨機抽樣，從n到m抽k個
e = np.random.randint(1,10,10) 
e

array([6, 3, 6, 1, 6, 9, 1, 8, 2, 9])

## np.random.standard_normal(n) 標準常態分佈抽 n 個

In [55]:
#  標準常態分佈抽 n 個
e = np.random.standard_normal(10) # 1~10, integers
e

array([ 0.08445935, -0.19277762, -0.56151888, -1.61922429, -0.18763411,
       -0.34518861,  1.74419881, -1.29383476,  0.62452789,  0.91810219])

## np.random.standard_normal(u,s,n) 常態分佈，平均值 u, 標準差 s，抽 n 個

In [56]:
# 常態分佈，平均值 u, 標準差 s，抽 n 個
# u=60，s= 7，n= 10
# normal()
e = np.random.normal(60,7,10) 
e

array([58.02866811, 48.39224164, 59.84656302, 64.95529085, 54.91328762,
       50.20051489, 74.5526388 , 64.51058658, 58.04556348, 73.26643911])

## np.random.uniform(a,b,n) 均等分佈，從a到b，抽 n 個

In [57]:
# 均等分佈，從a到b，抽 n 個
# a=1, b=10, n=10
e = np.random.uniform(1,10,10)
e

array([6.70566776, 7.35647244, 9.6368881 , 2.43526838, 3.20881071,
       6.74238842, 8.57833321, 8.89734566, 8.85169629, 2.18415691])

## .vstack([a,b]) 垂直合併

In [58]:
# 垂值合併
a = np.ones((4,5))   # 隨機選取常態分佈值  
b = np.zeros((4,5))   # 隨機選取常態分佈值
c=np.vstack([a,b])
c

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

##  .htack([a,b]) 水平合併

In [59]:
# 水平合併
d=np.hstack([a,b])
d

array([[1., 1., 1., 1., 1., 0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1., 0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1., 0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1., 0., 0., 0., 0., 0.]])

In [62]:
## 如果維度不對，則出現錯誤訊息（4,4) (2,8)
import sys
try:
    e=np.hstack([c,d])
    e
except:
    print ('something wrong, numbers not match')

something wrong, numbers not match


# 練習__
* 擲骰子，一次擲三個，計算點數總和。總共擲100次，記錄每次擲的點數。

In [151]:
a=np.random.randint(1,6,3)
for i in range(49):
    c=np.random.randint(1,7,3)
    # 垂直往下加
    a=np.vstack([a,c])
a  

array([[2, 2, 3],
       [5, 2, 5],
       [4, 2, 3],
       [1, 4, 3],
       [5, 3, 4],
       [3, 3, 1],
       [1, 4, 1],
       [2, 3, 1],
       [1, 4, 5],
       [5, 1, 2],
       [2, 2, 2],
       [3, 3, 5],
       [4, 3, 5],
       [1, 3, 4],
       [5, 3, 5],
       [6, 3, 5],
       [3, 3, 5],
       [4, 5, 6],
       [2, 4, 1],
       [3, 3, 4],
       [6, 1, 5],
       [4, 1, 3],
       [4, 5, 6],
       [3, 1, 6],
       [3, 6, 4],
       [4, 5, 3],
       [3, 6, 6],
       [1, 5, 1],
       [3, 5, 2],
       [3, 4, 5],
       [2, 6, 3],
       [4, 1, 4],
       [5, 1, 1],
       [1, 4, 4],
       [5, 6, 4],
       [4, 5, 1],
       [4, 6, 6],
       [6, 6, 3],
       [1, 5, 5],
       [6, 3, 2],
       [4, 6, 2],
       [1, 5, 1],
       [2, 6, 4],
       [5, 2, 2],
       [5, 5, 2],
       [2, 5, 2],
       [3, 1, 3],
       [4, 5, 1],
       [2, 3, 4],
       [3, 3, 6]])

## 顯示array 的資訊 .dtype, .shape,  .ndim, .size

In [152]:
a.dtype # 元素型態

dtype('int32')

In [153]:
a.ndim  #  dimention

2

In [154]:
a.shape  # rows, columns

(50, 3)

In [155]:
a.size  # 總共元素個數

150

# indexing and slicing of array elements

In [156]:
print (len(a))
# 每次擲骰子的第一個點數
a[:,0]

50


array([2, 5, 4, 1, 5, 3, 1, 2, 1, 5, 2, 3, 4, 1, 5, 6, 3, 4, 2, 3, 6, 4,
       4, 3, 3, 4, 3, 1, 3, 3, 2, 4, 5, 1, 5, 4, 4, 6, 1, 6, 4, 1, 2, 5,
       5, 2, 3, 4, 2, 3])

In [157]:
# 第三次擲骰子的點數
a[2,:]

array([4, 2, 3])

In [158]:
# 最後一次擲的骰子
a[-1]

array([3, 3, 6])

## sort()

In [159]:
# 各欄獨立，分別排序。第一個維度，各元素同樣位置的元素排序
a0=np.sort(a, axis=0)
a0

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 2, 1],
       [2, 2, 1],
       [2, 2, 2],
       [2, 2, 2],
       [2, 2, 2],
       [2, 3, 2],
       [2, 3, 2],
       [2, 3, 2],
       [2, 3, 2],
       [3, 3, 2],
       [3, 3, 3],
       [3, 3, 3],
       [3, 3, 3],
       [3, 3, 3],
       [3, 3, 3],
       [3, 3, 3],
       [3, 3, 3],
       [3, 3, 3],
       [3, 4, 4],
       [3, 4, 4],
       [4, 4, 4],
       [4, 4, 4],
       [4, 4, 4],
       [4, 4, 4],
       [4, 5, 4],
       [4, 5, 4],
       [4, 5, 4],
       [4, 5, 5],
       [4, 5, 5],
       [4, 5, 5],
       [4, 5, 5],
       [5, 5, 5],
       [5, 5, 5],
       [5, 5, 5],
       [5, 5, 5],
       [5, 6, 5],
       [5, 6, 5],
       [5, 6, 6],
       [5, 6, 6],
       [6, 6, 6],
       [6, 6, 6],
       [6, 6, 6],
       [6, 6, 6]])

In [160]:
# 各列獨立，分別排序，第二個維度，各元素排序
a1=np.sort(a, axis=1)       
a1

array([[2, 2, 3],
       [2, 5, 5],
       [2, 3, 4],
       [1, 3, 4],
       [3, 4, 5],
       [1, 3, 3],
       [1, 1, 4],
       [1, 2, 3],
       [1, 4, 5],
       [1, 2, 5],
       [2, 2, 2],
       [3, 3, 5],
       [3, 4, 5],
       [1, 3, 4],
       [3, 5, 5],
       [3, 5, 6],
       [3, 3, 5],
       [4, 5, 6],
       [1, 2, 4],
       [3, 3, 4],
       [1, 5, 6],
       [1, 3, 4],
       [4, 5, 6],
       [1, 3, 6],
       [3, 4, 6],
       [3, 4, 5],
       [3, 6, 6],
       [1, 1, 5],
       [2, 3, 5],
       [3, 4, 5],
       [2, 3, 6],
       [1, 4, 4],
       [1, 1, 5],
       [1, 4, 4],
       [4, 5, 6],
       [1, 4, 5],
       [4, 6, 6],
       [3, 6, 6],
       [1, 5, 5],
       [2, 3, 6],
       [2, 4, 6],
       [1, 1, 5],
       [2, 4, 6],
       [2, 2, 5],
       [2, 5, 5],
       [2, 2, 5],
       [1, 3, 3],
       [1, 4, 5],
       [2, 3, 4],
       [3, 3, 6]])

In [161]:
# 所有元素值依大小排序
a3=np.sort(a, axis=None)
a3

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
       3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4,
       4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 5, 5, 5, 5, 5, 5, 5,
       5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5,
       6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6])

## 比較 擲骰子，存為list of tuple

In [166]:
b=[]
for i in range(49):
    c=np.random.randint(1,7,3)
    # 垂直往下加
    b.append(list(c))
b[:10]  

[[6, 6, 5],
 [5, 3, 1],
 [5, 2, 3],
 [2, 5, 2],
 [5, 2, 5],
 [5, 4, 4],
 [6, 6, 5],
 [6, 1, 6],
 [5, 4, 1],
 [3, 3, 5]]

In [167]:
# 根據第一欄排序
b1=sorted(b,key=lambda x:x[0],reverse=False)
b1[:10]

[[1, 6, 3],
 [1, 5, 3],
 [1, 1, 5],
 [1, 1, 2],
 [1, 4, 4],
 [1, 6, 3],
 [1, 4, 2],
 [2, 5, 2],
 [2, 1, 6],
 [2, 6, 4]]

In [168]:
# 根據第二欄排序
b2=sorted(b,key=lambda x:x[1],reverse=False)
b2[:10]

[[6, 1, 6],
 [2, 1, 6],
 [6, 1, 3],
 [6, 1, 4],
 [1, 1, 5],
 [1, 1, 2],
 [4, 1, 5],
 [5, 1, 1],
 [5, 2, 3],
 [5, 2, 5]]

## 篩選 numpy array

In [170]:
# 大於 10 的 array
b=(a[a > 5])
b

array([6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6])

## 數學函數 sum(), cumsum(), average(), std()
* 數學函數 https://docs.scipy.org/doc/numpy/reference/routines.math.html 

In [171]:
# 最大值最小值
print (np.min(a))
print (np.max(a))

1
6


In [172]:
# 各欄或列加總 .sum()
print (np.sum(a))  # Compute sum of all elements; prints "10"
print (np.sum(a, axis=0))  # Compute sum of each column; prints "[4 6]"
print (np.sum(a, axis=1))  # Compute sum of each row; prints "[3 7]"

519
[165 183 171]
[ 7 12  9  8 12  7  6  6 10  8  6 11 12  8 13 14 11 15  7 10 12  8 15 10
 13 12 15  7 10 12 11  9  7  9 15 10 16 15 11 11 12  7 12  9 12  9  7 10
  9 12]


In [173]:
# 每次擲骰子的點數總合，排序
score=np.sort(np.sum(a, axis=1))
score

array([ 6,  6,  6,  7,  7,  7,  7,  7,  7,  7,  8,  8,  8,  8,  9,  9,  9,
        9,  9,  9, 10, 10, 10, 10, 10, 10, 11, 11, 11, 11, 11, 12, 12, 12,
       12, 12, 12, 12, 12, 12, 12, 13, 13, 14, 15, 15, 15, 15, 15, 16])

In [174]:
# 大於15的次數
b=len((score[score>=15]))
b

6

In [175]:
# 依欄累計加總 .cumsum()
a0=a.cumsum(axis=0)                         # cumulative sum along each column
a0

array([[  2,   2,   3],
       [  7,   4,   8],
       [ 11,   6,  11],
       [ 12,  10,  14],
       [ 17,  13,  18],
       [ 20,  16,  19],
       [ 21,  20,  20],
       [ 23,  23,  21],
       [ 24,  27,  26],
       [ 29,  28,  28],
       [ 31,  30,  30],
       [ 34,  33,  35],
       [ 38,  36,  40],
       [ 39,  39,  44],
       [ 44,  42,  49],
       [ 50,  45,  54],
       [ 53,  48,  59],
       [ 57,  53,  65],
       [ 59,  57,  66],
       [ 62,  60,  70],
       [ 68,  61,  75],
       [ 72,  62,  78],
       [ 76,  67,  84],
       [ 79,  68,  90],
       [ 82,  74,  94],
       [ 86,  79,  97],
       [ 89,  85, 103],
       [ 90,  90, 104],
       [ 93,  95, 106],
       [ 96,  99, 111],
       [ 98, 105, 114],
       [102, 106, 118],
       [107, 107, 119],
       [108, 111, 123],
       [113, 117, 127],
       [117, 122, 128],
       [121, 128, 134],
       [127, 134, 137],
       [128, 139, 142],
       [134, 142, 144],
       [138, 148, 146],
       [139, 153

In [176]:
# 依列累計加總
a1=a.cumsum(axis=1)                         # cumulative sum along each row
a1

array([[ 2,  4,  7],
       [ 5,  7, 12],
       [ 4,  6,  9],
       [ 1,  5,  8],
       [ 5,  8, 12],
       [ 3,  6,  7],
       [ 1,  5,  6],
       [ 2,  5,  6],
       [ 1,  5, 10],
       [ 5,  6,  8],
       [ 2,  4,  6],
       [ 3,  6, 11],
       [ 4,  7, 12],
       [ 1,  4,  8],
       [ 5,  8, 13],
       [ 6,  9, 14],
       [ 3,  6, 11],
       [ 4,  9, 15],
       [ 2,  6,  7],
       [ 3,  6, 10],
       [ 6,  7, 12],
       [ 4,  5,  8],
       [ 4,  9, 15],
       [ 3,  4, 10],
       [ 3,  9, 13],
       [ 4,  9, 12],
       [ 3,  9, 15],
       [ 1,  6,  7],
       [ 3,  8, 10],
       [ 3,  7, 12],
       [ 2,  8, 11],
       [ 4,  5,  9],
       [ 5,  6,  7],
       [ 1,  5,  9],
       [ 5, 11, 15],
       [ 4,  9, 10],
       [ 4, 10, 16],
       [ 6, 12, 15],
       [ 1,  6, 11],
       [ 6,  9, 11],
       [ 4, 10, 12],
       [ 1,  6,  7],
       [ 2,  8, 12],
       [ 5,  7,  9],
       [ 5, 10, 12],
       [ 2,  7,  9],
       [ 3,  4,  7],
       [ 4,  

In [177]:
# 平均值 .average()
print (np.average(a, axis=0))
print (np.average(a, axis=1))
print (np.average(a[0]))
print (np.average(a[:,2]))

[3.3  3.66 3.42]
[2.33333333 4.         3.         2.66666667 4.         2.33333333
 2.         2.         3.33333333 2.66666667 2.         3.66666667
 4.         2.66666667 4.33333333 4.66666667 3.66666667 5.
 2.33333333 3.33333333 4.         2.66666667 5.         3.33333333
 4.33333333 4.         5.         2.33333333 3.33333333 4.
 3.66666667 3.         2.33333333 3.         5.         3.33333333
 5.33333333 5.         3.66666667 3.66666667 4.         2.33333333
 4.         3.         4.         3.         2.33333333 3.33333333
 3.         4.        ]
2.3333333333333335
3.42


In [178]:
# 計算各列的加權平均值，依序列加權
wei=np.arange(0,50,1)
print (np.average(a[:,0], weights=wei))

3.363265306122449


In [179]:
# 標準差
print (np.std(a))
print (np.std(a, axis=0))
print (np.std(a, axis=1))

1.6109210615876455
[1.5132746  1.63229899 1.66240789]
[0.47140452 1.41421356 0.81649658 1.24721913 0.81649658 0.94280904
 1.41421356 0.81649658 1.69967317 1.69967317 0.         0.94280904
 0.81649658 1.24721913 0.94280904 1.24721913 0.94280904 0.81649658
 1.24721913 0.47140452 2.1602469  1.24721913 0.81649658 2.05480467
 1.24721913 0.81649658 1.41421356 1.88561808 1.24721913 0.81649658
 1.69967317 1.41421356 1.88561808 1.41421356 0.81649658 1.69967317
 0.94280904 1.41421356 1.88561808 1.69967317 1.63299316 1.88561808
 1.63299316 1.41421356 1.41421356 1.41421356 0.94280904 1.69967317
 0.81649658 1.41421356]


## exp(), sqrt()

In [180]:
# 指數
np.exp(a)

array([[  7.3890561 ,   7.3890561 ,  20.08553692],
       [148.4131591 ,   7.3890561 , 148.4131591 ],
       [ 54.59815003,   7.3890561 ,  20.08553692],
       [  2.71828183,  54.59815003,  20.08553692],
       [148.4131591 ,  20.08553692,  54.59815003],
       [ 20.08553692,  20.08553692,   2.71828183],
       [  2.71828183,  54.59815003,   2.71828183],
       [  7.3890561 ,  20.08553692,   2.71828183],
       [  2.71828183,  54.59815003, 148.4131591 ],
       [148.4131591 ,   2.71828183,   7.3890561 ],
       [  7.3890561 ,   7.3890561 ,   7.3890561 ],
       [ 20.08553692,  20.08553692, 148.4131591 ],
       [ 54.59815003,  20.08553692, 148.4131591 ],
       [  2.71828183,  20.08553692,  54.59815003],
       [148.4131591 ,  20.08553692, 148.4131591 ],
       [403.42879349,  20.08553692, 148.4131591 ],
       [ 20.08553692,  20.08553692, 148.4131591 ],
       [ 54.59815003, 148.4131591 , 403.42879349],
       [  7.3890561 ,  54.59815003,   2.71828183],
       [ 20.08553692,  20.08553

In [181]:
# 開根號
np.sqrt(a)

array([[1.41421356, 1.41421356, 1.73205081],
       [2.23606798, 1.41421356, 2.23606798],
       [2.        , 1.41421356, 1.73205081],
       [1.        , 2.        , 1.73205081],
       [2.23606798, 1.73205081, 2.        ],
       [1.73205081, 1.73205081, 1.        ],
       [1.        , 2.        , 1.        ],
       [1.41421356, 1.73205081, 1.        ],
       [1.        , 2.        , 2.23606798],
       [2.23606798, 1.        , 1.41421356],
       [1.41421356, 1.41421356, 1.41421356],
       [1.73205081, 1.73205081, 2.23606798],
       [2.        , 1.73205081, 2.23606798],
       [1.        , 1.73205081, 2.        ],
       [2.23606798, 1.73205081, 2.23606798],
       [2.44948974, 1.73205081, 2.23606798],
       [1.73205081, 1.73205081, 2.23606798],
       [2.        , 2.23606798, 2.44948974],
       [1.41421356, 2.        , 1.        ],
       [1.73205081, 1.73205081, 2.        ],
       [2.44948974, 1.        , 2.23606798],
       [2.        , 1.        , 1.73205081],
       [2.

# 矩陣運算

In [182]:
#identity matrix 單位矩陣
I = np.eye(4)  
print (I)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [183]:
x = np.array([[1,2,3,4],[3,4,5,6]])
y = np.array([[5,6,7,8],[7,8,9,10]])
print (x)
print (y)

[[1 2 3 4]
 [3 4 5 6]]
[[ 5  6  7  8]
 [ 7  8  9 10]]


In [184]:
# 轉置矩陣
xt=x.T
xt

array([[1, 3],
       [2, 4],
       [3, 5],
       [4, 6]])

## 矩陣的加減乘除


In [185]:
# 加
xay=x+y
xay

array([[ 6,  8, 10, 12],
       [10, 12, 14, 16]])

In [186]:
np.add(x, y)

array([[ 6,  8, 10, 12],
       [10, 12, 14, 16]])

In [187]:
# 減
np.subtract(x, y)

array([[-4, -4, -4, -4],
       [-4, -4, -4, -4]])

In [188]:
# 元素兩兩相乘
xpy=x*y
xpy

array([[ 5, 12, 21, 32],
       [21, 32, 45, 60]])

In [189]:
np.multiply(x, y)

array([[ 5, 12, 21, 32],
       [21, 32, 45, 60]])

In [190]:
# 內積，矩陣相乘，注意 dot 與 multiply 不同
# 轉置後方能相乘 2*4, 4*2
np.dot(x, y.T)
x.dot(y.T)

array([[ 70,  90],
       [122, 158]])

In [191]:
# 元素兩兩相除
xdy=x/y
xdy

array([[0.2       , 0.33333333, 0.42857143, 0.5       ],
       [0.42857143, 0.5       , 0.55555556, 0.6       ]])

## 反矩陣 np.linalg.inv()

In [192]:
xdy=x.dot(y.T)
inv_x = np.linalg.inv(xdy)
print (inv_x)

[[ 1.975 -1.125]
 [-1.525  0.875]]


In [193]:
# 矩陣和自己的反矩陣相乘等於單位矩陣
np.dot(xdy,inv_x)

array([[1., 0.],
       [0., 1.]])

## save(,), load(,) array

In [194]:
# save an array
np.save(path + "data/example.npy",b)

In [195]:
a1=np.load(path + "data/example.npy")
a1

array(6)

## numpy save and load dictionary
* 用pickle 亦可儲存 dictionarfy

In [196]:
## zip( ) 將兩個List 配對結合，再轉為字典變數
names = ['One', 'Two', 'Three', 'Four']
numbers = [1, 2, 3, 4]
d2 = zip(names,numbers)
dic1 = dict(d2)
print (dic1)

{'One': 1, 'Two': 2, 'Three': 3, 'Four': 4}


In [199]:
# path/dic1 為檔案儲存的路徑，必須存在這個資料夾
np.save(path + "data/dic1.npy", dic1)

In [200]:
dic1=np.load(path + "data/dic1.npy")
print (dic1)

{'One': 1, 'Two': 2, 'Three': 3, 'Four': 4}


# 提示
* numpy array 與 list 類同，可以進行多維度的資料整理，彼此也可以轉換。
* numpy 加強數學運算的功能。特別是抽樣，與矩陣運算，甚為常用。
* numpy array 裡面的元素，只能是數字，不能是字串、list 等其他的變數型態，list 則無此限制。

# 作業
* 擲骰子，每次擲十個，共鄭一千次。每次擲骰子十個點數之和大於50的機率有多少? 
* 請用 numpy.random 抽樣，計算大於50的次數與總共次數的比例，即可得機率。

In [1]:
random

NameError: name 'random' is not defined

In [ ]:
import random,datetime
ls=['林慈璿','樊志文','許駿傑','劉津秀','洪立穎','田梓伶','呂明陽','洪暐婷','吳孟津','廖柔瑄','廖家陞','梁育宸','周禮邦','劉柏彥','張舒萍','林勁凱','許祖信','黃緯易','潘冠宇','鄔磊融','陳書弘','湯雅媜','何建儒','林昱瑄','洪榕蓮','陳彥傑','劉昀沅','熊  庭','陳浩欣','歐秉昀','王禕梵','洪愷伶','馮意凡','侯依寧']

random.seed(datetime.datetime.now().time())
print(ls[random.randint(0,len(ls)-1)])

In [ ]:
#助教提醒

#方便用
line number #View -> togglelinenumber
shift+tab of func and property
?range

#縮排
(tab or shift+tab) and 選取

#垂直選擇
alt/option + mouse right

#dataframe用
'notepad++' 妙用

#統一編輯
ctrl/cmd 複數游標 #可以同時用來改變數




#快速選取用
(shift or (ctrl/cmd + shift)) and 方向鍵

#其他快捷鍵
home or cmd+up, end or cmd+down, pageup, pagedown
#ctrl/cmd+a, ctrl/cmd+r, ctrl/cmd+h, ctrl/cmd+f, win+d/m, ctrl/cmd+d